version: '3.9'

services:
  judgesystem:
    image: ghcr.io/yanorei32/yr32-judgesystem:latest@sha256:762b6b20cf1fedf7db2ff19e34e82570adabff69718528dd998f4e24eef8ea98
    hostname: judgesystem
    container_name: judgesystem__judgesystem
    init: true

    restart: unless-stopped
    user: root

    volumes:
      - type: bind
        source: ./practices.json
        target: /etc/practices.json
        read_only: true

      - type: bind
        source: ./users.json
        target: /etc/users.json
        read_only: true

    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 512M

    networks:
      judgesystem_cloudflared:

  cloudflared:
    image: cloudflare/cloudflared:2026.9.3@sha256:072c067d25ccbe61d46e18f0d0723255f2bb5304f7317caa95b27031520ff92c
    hostname: cloudflared
    container_name: judgesystem__cloudflared
    restart: unless-stopped

    environment:
      TUNNEL_METRICS: 0.0.0.0:9126
      TUNNEL_LOGFILE: /dev/stdout

    command: tunnel run --token ${TUNNEL_TOKEN}
    user: root

    networks:
      judgesystem_cloudflared:
      cloudflared_internet:
      prometheus__cloudflared:
        aliases:
          - judgesystem__cloudflared

    deploy:
      resources:
        limits:
          memory: 128m

networks:
  prometheus__cloudflared:
    name: prometheus__cloudflared
    external: true

  judgesystem_cloudflared:
    name: judgesystem__judgesystem_cloudflared
    internal: true

  cloudflared_internet:
    name: judgesystem__judgesystem_internet
