version: '3.9'

services:
  judgesystem:
    image: ghcr.io/yanorei32/yr32-judgesystem:latest@sha256:04b47b0ce7d6da4d05648efd046f1e372b544db64e08b39878d387e05a18139d
    hostname: judgesystem
    container_name: judgesystem__judgesystem
    init: true

    restart: unless-stopped
    user: root

    volumes:
      - type: bind
        source: ./practices.json
        target: /etc/practices.json
        read_only: true

      - type: bind
        source: ./users.json
        target: /etc/users.json
        read_only: true

    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 512M

    networks:
      judgesystem_cloudflared:

  cloudflared:
    image: cloudflare/cloudflared:2026.8.2@sha256:0aa26e284f05e6c77ae375b8c9c11d9eb6a448fb7bcd8d40f31cb6176189eb38
    hostname: cloudflared
    container_name: judgesystem__cloudflared
    restart: unless-stopped

    environment:
      TUNNEL_METRICS: 0.0.0.0:9126
      TUNNEL_LOGFILE: /dev/stdout

    command: tunnel run --token ${TUNNEL_TOKEN}
    user: root

    networks:
      judgesystem_cloudflared:
      cloudflared_internet:
      prometheus__cloudflared:
        aliases:
          - judgesystem__cloudflared

    deploy:
      resources:
        limits:
          memory: 128m

networks:
  prometheus__cloudflared:
    name: prometheus__cloudflared
    external: true

  judgesystem_cloudflared:
    name: judgesystem__judgesystem_cloudflared
    internal: true

  cloudflared_internet:
    name: judgesystem__judgesystem_internet
