version: '3.9'

services:
  judgesystem:
    image: ghcr.io/yanorei32/yr32-judgesystem:latest@sha256:d228b351e7e21e8a0e8fba1bbf5947636c4c7a28a96be7d7af1553099cc87d2c
    hostname: judgesystem
    container_name: judgesystem__judgesystem
    init: true

    restart: unless-stopped
    user: root

    volumes:
      - type: bind
        source: ./practices.json
        target: /etc/practices.json
        read_only: true

      - type: bind
        source: ./users.json
        target: /etc/users.json
        read_only: true

    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 512M

    networks:
      judgesystem_cloudflared:

  cloudflared:
    image: cloudflare/cloudflared:2026.7.1@sha256:188bb03589a32affed3cf4d0590565ffe67b78866e6b5582574afab2b705bafe
    hostname: cloudflared
    container_name: judgesystem__cloudflared
    restart: unless-stopped

    environment:
      TUNNEL_METRICS: 0.0.0.0:9126
      TUNNEL_LOGFILE: /dev/stdout

    command: tunnel run --token ${TUNNEL_TOKEN}
    user: root

    networks:
      judgesystem_cloudflared:
      cloudflared_internet:
      prometheus__cloudflared:
        aliases:
          - judgesystem__cloudflared

    deploy:
      resources:
        limits:
          memory: 128m

networks:
  prometheus__cloudflared:
    name: prometheus__cloudflared
    external: true

  judgesystem_cloudflared:
    name: judgesystem__judgesystem_cloudflared
    internal: true

  cloudflared_internet:
    name: judgesystem__judgesystem_internet
