name: lint actions

on:
  pull_request:
    paths:
      - '.github/workflows/**'

jobs:
  lint-actionlint:
    runs-on: ubuntu-22.04

    steps:
       - uses: actions/checkout@v4.0.0

       - uses: reviewdog/action-actionlint@v1.38.0
         with:
           github_token: ${{ secrets.GITHUB_TOKEN }}
           reporter: github-pr-check
